name: Build and Push Cloud Portfolio

on:
  push:
    branches:
      - main
    paths:
      - "cloud-portfolio/**"
      
permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-northeast-2
  AWS_ACCOUNT_ID: "245067526307"
  ECR_REPOSITORY: cloud-portfolio

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # 1. Checkout
      # ==========================================

      - name: Checkout
        uses: actions/checkout@v6


      # ==========================================
      # 2. AWS OIDC Authentication
      # ==========================================

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::245067526307:role/github-actions-hw-project
          aws-region: ${{ env.AWS_REGION }}


      # ==========================================
      # 3. Verify AWS Identity
      # ==========================================

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity


      # ==========================================
      # 4. Login to ECR
      # ==========================================

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.1.6


      # ==========================================
      # 5. Build and Push Docker Image
      # ==========================================

      - name: Build and push image

        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}

        run: |

          docker build \
            --platform linux/amd64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./cloud-portfolio

          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG